version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /infra/main
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /infra/bootstrap
    schedule:
      interval: weekly

